### ISSUE TITLE
Ansible playbook deploy_cluster.yml hangs waiting on control plane

### ISSUE THREAD

**Issue by samueljmello** [kuyio/openshift-okd-azure#1]
As the subject line states, running the deploy_cluster.yml hangs waiting for the control plane.

Inspection of the masters and monitoring journalctl reveals the following error in a loop:

> Unable to update cni config: No networks found in /etc/cni/net.d 

Inspection of /etc/cni reveals that no such directory exists.

It's clear that the network interface for the control plane is not coming up, therefore the k8s installation can't continue.

Did the deployment work for you? I ended up re-writing your  scripts into Terraform (to expedite the deployment of resources in parallel), but the inventory file stayed the same, save a few small problems with it (storage account key lacking quotes, oreg_auth_user causing pre-req failures, etc).

I'm just curious if you currently use this and have any ideas why the CNI portion is failing. One more tidbit of information; the Ansible task of "container_runtime : Ensure CNI configuration directory exists" skips all the nodes. I'm not sure why that is, but it seems to point to an issue with the node configuration.

Any help is appreciated. Thanks!

**Comment by nicbet** [comment]
@samueljmello Yes - the repository as published was used with several clients for their OKD deployments. I particularly created this repo as I was annoyed with existing published canonical examples not working ... ;-)

I've seen it hang at the `Waiting for Control Plane to become available...` step when DNS wasn't set up properly, i.e.: from `00-configuration.sh` in line `23`:

```
# Applications
# https://<application>-<namespace>.${CLUSTER_NAME}-${LOCATION}.${DNS_DOMAIN}
DNS_DOMAIN=company.org
```

you need to make sure that you have a DNS entry for the master/controller nodes set up in that zone, as the Playbooks will attempt to connect through that FQDN.

**Comment by samueljmello** [comment]
Thanks @nicbet 

I ended up porting your repo to Terraform for faster provisioning in Azure. It turned out that the Azure load balancing rules weren't being created correctly, thus traffic wasn't flowing to the masters and the Ansible playbook was unable to proceed.

For anyone else experiencing this problem, I would advise you to make sure traffic can reach your master nodes during the setup. The CNI error is normal and occurs until the SDN has been configured, but the masters have to be externally accessible through a VIP first.
